version: "3"
services:
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: Tweet
    volumes:
      - 'mongo:/data/db'
      - './scripts/utils/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro'
volumes:
  mongo: {}